### ISSUE TITLE
Incompatible with Vision 5e module

### ISSUE THREAD

**Issue by txm3278** [Eligarf/stealthy#102]
When using the Vision 5e Module, https://foundryvtt.com/packages/vision-5e, hidden tokens can be seen by everyone

![image](https://github.com/Eligarf/stealthy/assets/25332081/a40af5c1-fca3-476d-8ddb-5ff0aa107667)

**Comment by dev7355608** [comment]
Vision 5e 1.2.0 should be compatible with Stealthy now.

Compatibility code added to Vision 5e: https://github.com/dev7355608/vision-5e/blob/main/scripts/compatibility.mjs
