### ISSUE TITLE
PF2e Improvement - switch Stealth to the Hide/Sneak actions

### ISSUE THREAD

**Issue by apoapostolov** [Eligarf/stealthy#104]
Stealthy should apply its logic to Hide and Sneak basic actions (the best way to use them is the BAM macro from Workbench). These actions can have situational modifiers from items, feats, and more that won't apply to Stealth checks. Also, these are the right way to roll Stealth as a Secret check. 

This can be an option in Settings to apply the PF2 trigger to Stealth checks, but RAW should apply to the Hide and Sneak actions.

**Comment by Eligarf** [comment]
BAM is a great macro, solves some issues our group has now that we've started a PF2e campaign. We were using Hide and Seek actions that we had dragged onto our characters and the GM would roll the stealth check from the cards that those actions generated in the chat. Isn't this solved by simply having the players use BAM without needing any code to be changed?

**Comment by Eligarf** [comment]
I'll just go ahead and require the actions, it's what we are doing manually anyway. Will be in 3.10.0.
