### ISSUE TITLE
Stealthy not appearing on wall/door menu

### ISSUE THREAD

**Issue by TheStrollingDM** [Eligarf/stealthy#105]
The Stealthy menu options for doors are not appearing. Running V11 Stable - Patch 7 (Build 307)
![Screenshot 2023-08-11 085554](https://github.com/Eligarf/stealthy/assets/141999742/f664818e-d708-478a-9939-f641eb716321)

**Comment by Eligarf** [comment]
I'm not sure when this stopped working as I haven't touched that door code in a while. Clearly the data is missing.

**Comment by TheStrollingDM** [comment]
OK I'll try uninstalling the mod and reinstalling

**Comment by TheStrollingDM** [comment]
Reinstalled and still not showing at all :(

**Comment by Eligarf** [comment]
This is a real bug, I'm still working on updating the way the door UI now needs to get hooked into the system.
