### ISSUE TITLE
Pf1e tokens not hidden

### ISSUE THREAD

**Issue by dxwarlock** [Eligarf/stealthy#109]
I might be assuming what the module does incorrectly.

When I add tokens to the map, one player and one NPC.
I add them both, start combat.
Have the NPC roll stealth (he gets a 44, player cannot beat this with a 20).
He gets 'hidden' applied as a condition/buff.
PC can still see his token, despite the take 10 turned off, and spot disabled just incase.

I have tried every combination of options and spot settings I can find. But the NPC is never invisible to the player.

And I missing some setting, or misunderstanding the use of the module?

This is on Foundry v11.307 and Pathfinder v9.4

**Comment by Eligarf** [comment]
In trying to reproduce this, it seems to work fine on my local player client, but I noticed that in the GM view, when you click on one of the tokens that shouldn't be able to see the hiding one, it doesn't actually disappear until you hover the mouse pointer over the hiding token. I turned on the logging in Stealthy, and in either case it is correctly detecting that the hiding token can't be seen, but for some reason the effect is delayed until you interact with the hiding token via mouse. If you enable Stealthy logging for the player client, do you see messages like 'stealthy | Becca's undefined can't see Tripp's 44' while the token remains visible on the canvas?

**Comment by dxwarlock** [comment]
I've managed to figure out what it is. Took me a bit. I got the same but opposite experience of result.

People can see the hidden tokens, until they move thiers.(we wasn't moving as we was testing things, wasn't a real game)
If NPC rolls stealth, and players can see him. Not until they move themselves (even by rotating their token) does he disappear.

(same for when they can win to see them, they cannot see them until they 'wiggle' thier token)

Id disabled all modules but the three needed to see if one of them was causing it. Same result.
I'll turn on debugging when I get a chance to get back into testing it and let you know what it returns.

**Comment by Eligarf** [comment]
There are a couple of gotcha's I run into, just in case:
* Having both tokens be friendly but having 'Only test Perception in combat' set.
* Not having vision on tokens

Are you running in Forge? I've only really tested the PF1 stuff in a local Foundry install and perhaps there is some wrinkle with Forge that I'm missing...

**Comment by dxwarlock** [comment]
It's not forge, its a server install on a rack box I rent running in the CMD window server mode.
I did some debugging but didnt see/get anything useful:
`Foundry VTT | Created ChatMessage with id [vdLpYpYDN0GmEiZy]
stealthy.js:78 stealthy | rollStealth {actor: ActorNPCPF, message: ChatMessagePF}actor: ActorNPCPF {name: 'Drake, Desert Drake', type: 'npc', img: 'moulinette/images/custom/Tokens/1125/81482-Dragon_Red.png', system: {…}, #validationFailures: {…}, …}message: ChatMessagePF {type: 5, timestamp: 1692809059869, flavor: '', content: '<span class="flavor-text">\n  <a data-tooltip="PF1.…    </div>\n    </section>\n</div>\n\n  </div>\n</div>', #validationFailures: {…}, …}[[Prototype]]: Object
stealthy.js:78 stealthy | RefreshPerception
stealthy.js:78 stealthy | RefreshPerception`
That is the drake rolling stealth. And player can still see them until I or the player 'wiggles' the PC be it moving or rotating. I have passive checks off, the roll is high enough to beat players perception 'just' incase passive was still triggering.

And this is a gif of having to wiggle to PC token for them to see them (same for them disappearing after stealth, just easier with two windows to capture them seeing them as a gif):
https://imgur.com/XShGaNn

What odd, is SOMETIMES when we roll stealth, it works and they 'poof' invisible as expected. But its maybe 1/3rd of the time?

**Comment by Eligarf** [comment]
Sounds like some kind of timing issue - I'll try putting a 1 second wait in between the roll stealth processing and the request to refresh the canvas perception.

Does it matter if they refresh the browser via F5 whether they can see the hidden thing?

**Comment by dxwarlock** [comment]
You mean if they refresh does the token they couldn't/could see changes state without doing anything else? I can test and see.

Thanks for looking into it. Hate to create an issue case for such a non-critical situation as I can just 'wiggle' the players that didn't move on turns that stealth/spot happen.

Is it a limitation of the user settings perhaps? I am not familiar with how Foundry does the play area draw. But the last VTT we used did not update the play area for some players unless something on it changed depending on their performance settings.
I played with the graphic settings to see if that was the case here. But unsure if foundry only sends new info when it 'needs' to (sort of like its a 'screenshot/snapshot' of the canvas, that sends a new one only when it changed).

**Comment by Eligarf** [comment]
Updating the play area was exactly what the RefreshPerception() call is meant to do - and I broadcast that one to all the players so that any time anybody rolls stealth, all tokens are supposed to be redrawn.

**Comment by dxwarlock** [comment]
I cannot find a rhyme or reason for a pattern on it.
Sometimes it works, sometimes it needs a wiggle, and sometimes they disappear or reappear for only some people and not others.
It's still usable perfectly fine long as I keep that in mind.
At this point I'm going to assume its particular to my setup. As it was a v8 game, migrated to v9, now migrated to v11. With some animated maps, some not, and some tokens a gif. Could be related(?)

Feel free to close this until I can narrow down the cause, and if related to the module give you more info beyond "It's 1/2 broke".

**Comment by Eligarf** [comment]
I've done some restructuring on what, where, and when of the hooks I use in Stealthy and just got Stealthy 3.16.1 working with PF1 9.6 as I expect. Perhaps this will solve the timing issues you were running into?
