### ISSUE TITLE
[Request] Option to not use Passive Perception (5e)

### ISSUE THREAD

**Issue by megahead11** [Eligarf/stealthy#110]
Hi! I like the functionality of the module since it leads to some interesting possibilities, but, however, I'm running into a bit of an issue using it. Our group doesn't use Passive Perception as a perception floor, just for other specific circumstances. Would it be possible to get a 5e option where it doesn't use passive perception, and instead relies solely on the Spotting active effect or dice rolled?

**Comment by SpaceYeti1** [comment]
Just a thought, but I noticed just today that they have included a number in the lower left on your token options if you right click. It is the value of that token's perception. You can manually change that to whatever number you like.

That said, it would still be handy to set a default so you didn't have to continually change the number manually.

**Comment by Eligarf** [comment]
Why not. This will be added in 3.12.
