### ISSUE TITLE
Compatibility with Dice so Nice

### ISSUE THREAD

**Issue by MotoMoto1234** [Eligarf/stealthy#115]
The banked second perception roll if you have that setting on in stealthy is not respecting blind roll mode.  So the second d20 which literally only shows up as a 3d dice roll, is showing its face in DSN therefore somewhat spoiling a blind perception roll.  Desired behavior is to fully hide it from 3d dice or make it follow the rollmode of its twin roll and do ??? on the dice face.

**Comment by Eligarf** [comment]
I went ahead and hid this from the 3d roller. It will show up in the 3.15 release
