### ISSUE TITLE
Perception checks don't create/update perception effect

### ISSUE THREAD

**Issue by Pelant** [Eligarf/stealthy#117]
For some reason the module is not creating the spot effect on the tonkens and it isn't updating the value of the perception check.
The stealth checks works as intended.
If I create the effect manually the box to overwrite the perception value appers (image):
![Captura de tela 2023-12-08 162038](https://github.com/Eligarf/stealthy/assets/153319950/b9e6e2fc-ce6a-449d-a03f-9a95dbd9db8c)

I tried putting the system in english, but it didn't work as well.
I'm using stealthy on DnD 5e.

**Comment by Janner3D** [comment]
~~I can confirm I'm also having this issue. It's a bit frustrating, as it kind of just breaks the whole functionality of this module. I'll be using Perceptive until this is fixed.~~

Update: Hitting this button seemed to solve the issue 😂

https://gyazo.com/28422fbe4ac493e898244dedea06264b
