### ISSUE TITLE
When in full darkness (but dim for viewers with night vision) the hidden token is still visible despite 

### ISSUE THREAD

**Issue by TrofimSelbs** [Eligarf/stealthy#118]
Hey, thank you for you module! It is super awesome 
I have some issues with implementation of -5 to passive perception when in Dim light for my 5e world.  In the first image you can see that the player's token has 13 passive perception. Veteran token has 12  in active stealth roll. In bright light he should be spotted automatically, but as he is located in the dim light (as per darkvision from player's token) he should not be seen. Player's perception is 13 and 13-5=8. Veteran has 12 stealth. Maybe I am missing something?  

![image](https://github.com/Eligarf/stealthy/assets/124184162/9f305d92-5e3d-49f6-90af-98089264f960)

**Here are my settings for the Stealthy module**
![image](https://github.com/Eligarf/stealthy/assets/124184162/538d5b21-3158-48b9-a5e8-9c7076092177)
![image](https://github.com/Eligarf/stealthy/assets/124184162/6f6e2396-3290-48ba-b396-864c5af52612)

**Comment by Eligarf** [comment]
You need to be using Token Light Condition to handle putting Dark/Dim conditions on the token. It is currently prohibitively expensive to dynamically test for light levels during a screen render.

**Comment by TrofimSelbs** [comment]
Ohhhhhhhhh that makes sense. There is a module called Token Light Condition. I assumed that it was some native feature.
