### ISSUE TITLE
Feature Request: Enable players to see (But not edit) their stealth/perception numbers on HUD

### ISSUE THREAD

**Issue by zk-sn** [Eligarf/stealthy#119]
The stealth & perception numbers only show up for the GM - it would be nice if players could see the stealth and perception numbers on their controlled tokens (but not edit those numbers)

**Comment by Eligarf** [comment]
This one has a decent chance of getting done once I work through all the vision-5e interactions. Not committing yet but is likely.

**Comment by Eligarf** [comment]
It's in 3.15.0
