### ISSUE TITLE
[FEATURE REQUEST] Change the icons

### ISSUE THREAD

**Issue by Kharmans** [Eligarf/stealthy#121]
Is it possible to let the GM change the icons the module uses?

**Comment by Eligarf** [comment]
You can use Convenient Effects for the Hidden/Spot icons and edit those however you choose. Look at the Hidden Effect Source and Spot Effect Source entries in the General Options section of Stealthy's game settings.

**Comment by Kharmans** [comment]
I don't use CE...

**Comment by Eligarf** [comment]
That is the only facility I have for this. Stealthy is very narrowly focused, so it isn't likely I'll be adding this capability within the module. I'll keep this in mind should I find some other reason to need to edit Stealthy's effects outside of CE.

**Comment by Eligarf** [comment]
I decided to go ahead and add the feature to the 3.15 release
