### ISSUE TITLE
Errors when Selecting a Token

### ISSUE THREAD

**Issue by Quasxen** [Eligarf/stealthy#122]
Just updated to the latest 3.14.3 version and now if I click on any Token I get the following error message. I'm then unable to de-select the token or do anything within that scene. 

Not sure what other information is needed to look in to this one, but will be happy to provide anything requested

![image](https://github.com/Eligarf/stealthy/assets/166070156/4485f962-5046-41ec-87a3-a9287cf3b641)

**Comment by Eligarf** [comment]
It looks like something has gone wrong earlier in the console log, could you send me the full log?  It's saying it doesn't know what a 'stealthy' is when clearly it's in the stealthy code. Perhaps something is trying to render before the setup is complete. You could also try and filter for 'stealthy' in the debug log for a shorter list.

**Comment by Quasxen** [comment]
Attached are some saved log files. The first is the full log when first logging in. The second is that same login log with Stealthy filtered
[Login_Log.txt](https://github.com/Eligarf/stealthy/files/14878178/Login_Log.txt)
[Stealthy_Filter_Login.txt](https://github.com/Eligarf/stealthy/files/14878179/Stealthy_Filter_Login.txt)

**Comment by zbyers26** [comment]
I had the same issue. Hard locks the whole scene. Most notable with any weather effects going. I reinstalled 3.14.1 and it's working like it did before the upgrade.

**Comment by Eligarf** [comment]
Fix is being pushed now. Thanks for reporting it. Perhaps in the future I shouldn't take 7 months off with code in-flight.

**Comment by zbyers26** [comment]
You're awesome and appreciated!
