### ISSUE TITLE
Bug: Applying Perception doesn't work.

### ISSUE THREAD

**Issue by ghost** [Eligarf/stealthy#123]
Hi,

since today applying perception doesn't seem to work. Stealth is working. All other modules, expect libWrapper and socketlib were deactivated. Got the follwing error. Hope you could help, or give me a hint, what I am doing wrong.
[localhost-1712431481814.log](https://github.com/Eligarf/stealthy/files/14894751/localhost-1712431481814.log)

foundry.js:3339 Uncaught (in promise) Error: undefined. This is not a registered game setting
[Detected 2 packages: stealthy, system:dnd5e]
    at ClientSettings.get (foundry.js:3339:42)
    at Engine5e.rollPerception (dnd5e.js:245:48)
    at Object.fn (dnd5e.js:94:20)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Actor5e.rollSkill (actor.mjs:1333:23)
get	@	foundry.js:3339
rollPerception	@	dnd5e.js:245
(anonymous)	@	dnd5e.js:94
#call	@	foundry.js:730
callAll	@	foundry.js:687
rollSkill	@	actor.mjs:1333
await in rollSkill (async)		
#call	@	foundry.js:730
callAll	@	foundry.js:687
rollSkill	@	actor.mjs:1333
await in rollSkill (async)		
_onRollSkillCheck	@	base-sheet.mjs:1175
dispatch	@	jquery.min.js:2
y.handle	@	jquery.min.js:2

**Comment by Eligarf** [comment]
Thanks for reporting. Am fixing now, will be in 3.15.1 release.
