### ISSUE TITLE
Only works once?

### ISSUE THREAD

**Issue by Garg80** [Eligarf/stealthy#124]
Using the Mod i have the issue of only once will the Hide or Spot values will be applied. Any rolls after the 1st Hide and 1st Spot will not apply the buff. Am I doing something wrong?

**Comment by Kharmans** [comment]
Yeah, I am having the exactly same problem. And it only applies on the literally first roll. If you roll for another actor, the effect will not be applied.

**Comment by Eligarf** [comment]
Found the merge error - a `Hooks.on` turned into `Hooks.once`. Fix incoming.
