### ISSUE TITLE
stealthy freezes when i interact with vehicle tokens

### ISSUE THREAD

**Issue by space0012** [Eligarf/stealthy#128]
I am no code r, but it seems to freeze whenever i click on a token that doesn't have stealth/perception stats ( like a vehicle token)

**Comment by Eligarf** [comment]
I don't see any issues like this on my end with a vehicle. Can you give me some kind of repro steps?

**Comment by Eligarf** [comment]
I see at least one issue, I'll see about getting out a fix soon.
