### ISSUE TITLE
Feature Request: Modify assuption for Passive Perception

### ISSUE THREAD

**Issue by Darkstand** [Eligarf/stealthy#130]
Allow the 'passive perception' base value to be manually set.

In my case I'm ussing PF1 but I want a lowered passive perception when not specifically trying to pay attention (and enforce an action cost to paying attention).

This is somewhat of a narrow usecase so I would not even say anything normally, but I suspect it might help other systems as well, especially if you can specify the attributes/skills/whateverweirdnessyoursystemuses that get added.  This way you could have a field that gets filled with whatever the default assumptions your system has (or blank/0 if none/not supported) but still be able to modify it.

(I actually was able to edit pf1.js to the value I wanted just to see if it would work, but any update wipes out the change so this is a lackluster solution at best)

**Comment by Eligarf** [comment]
I'll keep this in mind for something to tackle once I've dealt with V12 stuff
