### ISSUE TITLE
Feature request: Option to not test for passive stealth

### ISSUE THREAD

**Issue by TrofimSelbs** [Eligarf/stealthy#131]
Thank you for your module! I was wondering if you could please include an option in the settings to stop testing for passive stealth. If there is already an option for this - I couldn't find it. I have a player and their PC has lost an eye. They have a disadvantage in perception now and it means that their passive is lower than 10. If the creature is not hiding, like an NPC - this player still won't see them. I know it is rules as written, probably, but I would love for him to not see enemies who are hiding and not just all creatures. Thank you for your kind work.

**Comment by Eligarf** [comment]
All of Stealthy's processing is based on finding a banked stealth roll on a token, so adding this feature would outside of the scope I currently envision for it. I'm glad the module has worked for you other than this, perhaps you can find some clever ways to use the 'limits' module to make some kind of workaround for your one-eyed PC?

**Comment by TrofimSelbs** [comment]
If the Stealthy module is looking for a banked stealth roll - maybe this “no passive stealth” option could set banked stealth roll at 0? And if they have rolled - it is changed while they are hiding? Thank you for giving it a thought anyway. I will look into the module that you have suggested!

**Comment by Eligarf** [comment]
Since you can override banked stealth/perception rolls in the Token HUD, you could try and give the NPCs a banked stealth roll. An actor's passive perception is an attribute tracked by the dnd5e system, perhaps there is an active effect you could add to lower the passive perception for the specific character to a value lower than the banked stealth you gave the NPCs.

**Comment by TrofimSelbs** [comment]
I think that this can work. Thank you!

**Comment by Eligarf** [comment]
If you are comfortable writing a macro, you could automate the banking of the set value. `stealthy.bankStealth(token,value)` is all you need. Something like ```canvas.tokens.controlled.forEach((t) => stealthy.bankStealth(t, 5))``` would do all selected tokens (not sure if I got the syntax right but something very close to that)

**Comment by TrofimSelbs** [comment]
Thank you for the macro, will see if it works! Since we last spoke I've thought of another, much more common situation, where having default stealth at 0 (unless they roll for it) would be better. If you still think that this is not needed - ok then. I just want to make my case:

If any PC, at any point during combat/exploration on a map will have at least one level of exhaustion - they won't be able to see any NPCs, even their allied NPCs. No one is trying to be hidden in this example and it is not an edge-case, like in my one-eyed PC example. 

Let me know what you think! I really do believe that this is a valuable feature.


![image](https://github.com/Eligarf/stealthy/assets/124184162/f558f2ee-2f2e-4c64-aa60-9871ba4cbc08)

**Comment by Eligarf** [comment]
Exhaustion gives dIsadvantage on ability checks which means that they would be using passive perception at a -5 penalty, it would take a house rule that says you don't see NPCs that aren't hiding if you have disadvantage on Perception. If your passive perception is 10, does it matter that it would have been a 15 without disadvantage in scene where nobody is hiding? I think I must be misunderstanding why exhaustion would make things undetected.

I'd also point you towards the Perceptive module, it has MANY more dials and knobs to control visibility between specific tokens - check out their *Channel* feature.
