### ISSUE TITLE
Stealthy menu not showing on walls if other modules adds to wall config

### ISSUE THREAD

**Issue by TheXeno30** [Eligarf/stealthy#138]
![image](https://github.com/Eligarf/stealthy/assets/135822719/8cdf0786-c4c5-4701-ba49-45ee76f57df0)

Stealthy menu not showing on walls if other modules adds to wall config.
Could be wall height, arms reach or door sounds or more... 

Is there a way to make room for all of them?

**Comment by Eligarf** [comment]
I can't repro this problem. Besides *Stealthy* and *Tagger*, I enabled *Designer Doors*, *Door Sounds*, *Wall Height*, and *Arms Reach* and saw all expected blocks in the dialog. I then tried exiting full-screen and shrinking my window to something that couldn't hold the full dialog, and when I then brought the dialog up, I was able to scroll up/down with the mouse wheel to see everything, but I notice you don't have a scrollbar on your dialog picture and I don't know why that would be. I'm a newbie to HTML so I don't think I can fix any issues within the dialog outside of *Stealthy*'s block. 

You might want to try [*Perceptive*](https://foundryvtt.com/packages/perceptive) for dealing with doors - they have a lot more controls and put their stuff in a new tab so it won't run into the issue of over-filling this dialog. It's like moving from a scooter to the batcycle however; with power comes responsibility...

**Comment by TheXeno30** [comment]
Thanks - properly some module messing with it... btw. awesome module. My thief friends are going to love this :)

**Comment by TheXeno30** [comment]
Think it might be some of the more heavy modules thats messing with your module, so maybe you should go for the tab solution too to counter this :)

**Comment by Eligarf** [comment]
Which browser do you run with? I'm curious if that might be a factor in this.

I'm glad you like the module - it was born out of me playing a gloomstalker and getting tired of hassling with the GM about which tokens could or couldn't see me.

**Comment by Eligarf** [comment]
I don't currently plan on doing any more work with Doors, so I'm going to close this. I'll keep the idea of having a separate tab for Stealth in mind should things change.
