### ISSUE TITLE
[Translation] RU

### ISSUE THREAD

**Issue by VirusNik21** [Eligarf/stealthy#146]
I made a translation of your module into Russian. Please add it to the next build.
[ru.json](https://github.com/user-attachments/files/16077638/ru.json)

**Comment by Eligarf** [comment]
Thanks for the translation!

I'm adding these lines for the next release, could you give me translations for them as well?

```
    "gIDimThreshold": {
      "name": "Global Illumination dim light threshold",
      "hint": "On scenes with GI enabled, bright light exposure is assumed unless the darkness level exceeds the scene's GI threshold multiplied by this factor, yielding dim light. Use 1.0 to transition directly from bright to dark."
    },
```

**Comment by VirusNik21** [comment]
Yes Of corse
"name": "Порог яркости глобального освещения (GI)",
"hint": "В сценах с включенным GI предполагается яркое освещение, пока уровень темноты не превысит порог GI сцены, умноженный на этот коэффициент, что приведет к тусклому освещению. Используйте 1,0 для прямого перехода от яркого света к темноте."

**Comment by Eligarf** [comment]
Will be in 4.5.0 release
