### ISSUE TITLE
[bug report] Spot duration

### ISSUE THREAD

**Issue by VirusNik21** [Eligarf/stealthy#147]
I encountered a strange bug - for some reason the Spot effect is no longer set with a duration of 6 seconds. I tried resetting the world settings - it doesn't help.
It works as it should if you create a completely new world and test there.
The problem is that this happened in my adventure and I have no way to fix it.
Maybe you can find the cause. 
In the archive attached test world in which this problem is presented.
![123123123123123](https://github.com/Eligarf/stealthy/assets/150345729/45f8298d-f2ec-4c47-97f1-562a322efd4c)
link for a test world with issue
https://drive.google.com/file/d/1XIPoDeb1L5aWZQdT5f_B6jYZptFJcT6w/view?usp=sharing

**Comment by Eligarf** [comment]
It only adds the duration when creating a new Spot effect during combat (once something gets added to the encounter tracker). If an actor has the Spot effect on when combat is active, it currently leaves the existing effect alone. I'll add some code when rolling perception during combat to force a duration if there wasn't one already on the Spot effect.

**Comment by VirusNik21** [comment]
Great, thank you very much. I got it. I've been racking my brain trying to find the cause, but I overlooked that point).
