### ISSUE TITLE
Player see what the DM cannot.

### ISSUE THREAD

**Issue by Hooskin** [Eligarf/stealthy#151]
![image](https://github.com/user-attachments/assets/69d428de-0a01-4fc4-bd61-e783005d65de)
Left is my DM screen, and right is my player screen i've been trying for 3 hours to fix it, all my setting are the default one. 

Ps : Using Vivaldi, but I even tried on Edge, it does the same.

**Comment by Eligarf** [comment]
Try turning on the debug log for Stealthy in the game settings, then open the browser console (F12 usually) and look for lines that start with `stealthy |`. You may need to refresh afterward just to get a clean log (you can add 'stealthy' as a filter to the console). If you can get me the logs from both views perhaps that might shed some light.

I haven't seen this before, I'll try and help as I can.

**Comment by Hooskin** [comment]
It seems the issue was mostly due to the module GM Vision. Which is weird because even in a blank one I had that issue, it seems to have been fixed with the last update. Sorry for the bothering.
