### ISSUE TITLE
[4.2.1 Stealthy] Changing the bank setting has an issue

### ISSUE THREAD

**Issue by MotoMoto1234** [Eligarf/stealthy#153]
If you prep a session with X amount of actors having a banked roll stored on a token flag, then you change the bank stealth setting to store it in the effect/actor instead, then those existing actors will be unable to have their banked token flag cleared unless you go into the console and clear them the hard way.  The token hud is unresponsive to edits to the banked token flag's value, it constantly resets to the token flags number as if that becomes the new base instead of zero/null.

**Comment by MotoMoto1234** [comment]
If you roll a new stealth roll you get the hidden CE effect and that roll does override the original token flag while the ae is in effect, but the token flag underneath becomes the new floor for when the CE is removed every time.

**Comment by Eligarf** [comment]
Is this V11 w/Convenient Effects?
Just a thought, one workaround might be to switch the bank setting back to original setting, then clear out banked value.

**Comment by Eligarf** [comment]
Found the issue where, for backwards compatibility, it wasn't checking to see if a stealth effect was pre-existing on the actor before assuming that a change should go to the token. The stealth effect always has priority over token flags until the effect is removed, so this should take care of it.
