### ISSUE TITLE
Not working in my PF1e game

### ISSUE THREAD

**Issue by Belgaron** [Eligarf/stealthy#155]
I remember (back when it worked) it would add a "spot" buff and a "hide" buff... not sure about the second one. 

Now it doesn't add anything, but I did save the spot buff and if I put it on a player... the spot/perception seems to be working. The box with the number appears on the token hud. But I can't get the "stealth" part to do anything. I think the buff used to be called hide or hiding but adding both does nothing. I can't get that stealth # to show up.

Anyway, def not working on its own. Be nice if I could get that "stealth" buff or whatever to work even if I have to do it manually. Loved this mods functionality.

**Comment by Eligarf** [comment]
It will be fixed in 4.6.2 - pretty obvious syntax error I missed that somehow didn't crash my testing.
