### ISSUE TITLE
Translation of effect names

### ISSUE THREAD

**Issue by lucaspicerni** [Eligarf/stealthy#32]
Hi! Excellent module! For the purpose of translating the module, it would be great if it were possible to configure the name of the effects created by it. Are there any intentions to provide this in future versions? Thanks!

**Comment by Eligarf** [comment]
Thanks! I did set it up to support languages, but I've only filled out the en.json file. I'd love any help in getting other languages set up.

**Comment by lucaspicerni** [comment]
I'm a native Brazilian Portuguese speaker, I'll provide translation into my language later this week!

**Comment by Eligarf** [comment]
Thanks, I'll get this in the next release. I realized I didn't put the "Umbral Sight" label in the language file, would that be "Visão Umbral"?

**Comment by lucaspicerni** [comment]
Yes!

**Comment by Eligarf** [comment]
It's in v2.2.0.
