### ISSUE TITLE
[Bug] GM Spot toggle removes wrong status effect

### ISSUE THREAD

**Issue by LukasPrism** [Eligarf/stealthy#43]
It looks like toggling off the Active Spot is removing the first AE or condition on all the players instead of the Spot condition. You can toggle Active Spot on/off several times to get rid of every effect on the players. I think you can see why this is a huge problem.

Cheers!

**Comment by Eligarf** [comment]
Yup, two errors compounded on themselves, but is fixed now pending release in 1.6.0
