### ISSUE TITLE
PF1: better cleanup for the spot/hidden effects

### ISSUE THREAD

**Issue by Eligarf** [Eligarf/stealthy#51]
Stub is in place, just needs actual logic.

**Comment by Eligarf** [comment]
pf1: actually seems to "work"
    - I assume take-10 perception for tokens without an active spot effect. It isn't RAW, but perhaps this is acceptable to the PF1 community.
    - the PF1 actor sheet UI doesn't seem to have a way to delete the effects once they've been added by rolling

**Comment by Eligarf** [comment]
Perhaps these can be made into buffs? Stealthy itself isn't dependent on using an Active Effect per se, just something that behaves like an active effect.

**Comment by RoyRandom** [comment]
I love this mod, but once the "eye" symbol appears, there is no way to remove it. Its not showing as a buff and I dont think I can remove it without totally recreating the character...an
![Screenshot 2023-05-26 153203](https://github.com/Eligarf/stealthy/assets/112774357/634da9cf-2504-434a-9965-937649777845)
y ideas.

**Comment by Eligarf** [comment]
There are a couple of workarounds in the [wiki](https://github.com/Eligarf/stealthy/wiki/Pathfinder-1e). The 'Visual Active Effects' module also gives a way to delete by right-clicking the effect that shows up in the top-right of the screen when the token is selected.

**Comment by Eligarf** [comment]
This is fixed in v3.8.0
