### ISSUE TITLE
PF2e: Adapt Stealthy active effects

### ISSUE THREAD

**Issue by Eligarf** [Eligarf/stealthy#52]
The logic and skill hooks have been installed, but I ran into the problem where Active Effects don't work in PF2E, meaning heavy lifting is going to be required.

**Comment by apoapostolov** [comment]
Hello @Eligarf would you be interested in paid commissioned support for PF2? I would be trilled to help also with rule clarifications and suggestions how the mod could potentially be useful for PF2 system.

**Comment by Eligarf** [comment]
Got as far as injecting the status values into the actor, and am able to adjust the results via token buttons as in PF1 or Dnd5e, but the next step get way deeper since the stealth tests have no effect on the rendered scene. Returning 'false' from the vision test is supposed to reject the token from being drawn, but pf2e does something nonstandard. Sigh.

**Comment by AlexTamVo** [comment]
Would it be possible to have the effect where the token is shrouded instead? This is considering PF2E rules where a creature that wants to use the Hide Action rolls stealth and compares it to the perception DC of those around it. Creatures that fail the check can still "see" them, but have to roll a flat check to target them. Having the visual indicator would be useful for PF2E.

![image](https://user-images.githubusercontent.com/70011864/211219326-8d480694-f088-483d-a44e-3c114604635d.png)
