### ISSUE TITLE
Dnd4e: system doesn't use DetectionModeBasicSight.prototype.testVisibility

### ISSUE THREAD

**Issue by Eligarf** [Eligarf/stealthy#56]
So patching it doesn't do anything. Something better to patch?

**Comment by dev7355608** [comment]
If this were the case, then other modules would be affected too (Perfect Vision, Levels, Alternative Token Visibility). Dnd4e doesn't seem to change anything about vision modes or detection modes at all. `DetectionModeBasicSight#testVisibility` was called when I tested it just now.

**Comment by Eligarf** [comment]
I'm an idiot - The default character didn't have vision enabled on the token. Totally derped.

Thanks!
