### ISSUE TITLE
Don't put effects on prototype actor if unlinked

### ISSUE THREAD

**Issue by Eligarf** [Eligarf/stealthy#58]
Would be better to put the effect on the token rather than the actor

**Comment by tposney** [comment]
effects applied to token.actor won't affect the prototype actor, rather they will only exist on the token copy of the actor.

**Comment by Eligarf** [comment]
This was happening because someone was calling actor.rollSkill() in a macro. As you mention, the fix was to call token.actor.rollSkill() instead, but I'd like to be able to detect this case automatically and not apply the active effect. Do you know how to detect whether an actor is an unlinked prototype?

**Comment by Eligarf** [comment]
New token-centric makes this just go away
