### ISSUE TITLE
DnD5e Error - Effect Hidden could not be found 

### ISSUE THREAD

**Issue by ref2335** [Eligarf/stealthy#63]
When making a stealth check the error in description is shown but Hidden effect is placed on token.

Console error shows:

  | fetch | @ | foundry.js:59187
-- | -- | -- | --
  | notify | @ | foundry.js:59114
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | notificationNotify | @ | utils.js:3266
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:616
  | 🎁Notifications.prototype.notify#0 | @ | libWrapper-wrapper.js:189
  | error | @ | foundry.js:59150
  | addEffect | @ | effect-interface.js:189
  | updateOrCreateEffect | @ | stealthy.js:108
  | rollStealth | @ | dnd5e.js:143
  | (anonymous) | @ | dnd5e.js:9
  | #call | @ | foundry.js:724
  | callAll | @ | foundry.js:681
  | rollSkill | @ | actor.mjs:906
  | await in rollSkill (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | doRollSkill | @ | patching.js:157
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:616
  | 🎁CONFIG.Actor.documentClass.prototype.rollSkill#0 | @ | libWrapper-wrapper.js:189
  | _onRollSkillCheck | @ | base-sheet.mjs:1164
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

**Comment by Eligarf** [comment]
What version of Stealthy were you running, and what is the value shown for "Source for Hidden and Spot effects" in Stealthy's game settings? Thanks.

**Comment by ref2335** [comment]
I am running Stealthy 2.1.0 & you are correct CE doesn't have a "Hidden" effect to leverage....strangely it places a hidden effect on the token nevertheless.  Incidentally getting the same error for the "Spot" effect.

**Comment by Eligarf** [comment]
It is falling back to the default effects I create if it isn't overridden. You can either add an effect in CE or change the source to 'Stealthy' in that setting. When setting the default it looks for Hidden/Spot effects in those sources before choosing them, so I'm not sure why it thought that it found one. No matter, I'm putting some guards in place to make sure it doesn't get to the point of showing a CE error in this case and will cleanly fall back.
