### ISSUE TITLE
Bug with the door icon and the automatic secret door detection option "enabled"

### ISSUE THREAD

**Issue by Fridan99** [Eligarf/stealthy#80]
Foundry vtt v10.291
System dnd5e 2.0.3
Stealthy 3.0.1

If you have the automatic secret door detection option "enabled", if a secret door or normal door is created, the door icon does NOT appear. It only appears when F5 (refresh). The same when you lock or unlock the door, the icon does not update until F5 (refresh). 

By deactivating the automatic detection secret door, the error disappears. 

In principle, no error is displayed on the console. Or at least I am not able to see it.

**Comment by Eligarf** [comment]
Verified this is an issue. Looking at it.

**Comment by Eligarf** [comment]
Injecting libWrapper overrides into an object hierarchy has some unexpected side effects. Gonna take some study/experimentation to figure out how to proceed, so I've disabled the feature for now. Thanks for reporting it.

**Comment by Fridan99** [comment]
I hope you will be able to solve the problem in the future, as the automatic secret door detection function is very useful.  Thx

**Comment by Heljspe** [comment]
Would there possibly be any chance of getting an option to still use the doors even if it's 'buggy'? 🙏 
This week's game session was relying on quite a few secret doors and I was really looking forward to it. 😅
Can't find another module that does anything even similar.

**Comment by Fridan99** [comment]
Heljspe, you can download the version 3.0.1 zip file, and downgrade the module version replacing the module folder with the current 3.0.1 one...

https://github.com/Eligarf/stealthy/releases

**Comment by Eligarf** [comment]
I'll re-enable this with a warning about the icon behavior which I still haven't been able to figure out.

**Comment by Eligarf** [comment]
Fixed this by allowing regular doors to hide rather than trying to show secret doors.

**Comment by Fridan99** [comment]
Have you asked in discord? #module-troubleshooting or #module-discussion.....About how to get around the problem with the secret door?

Maybe someone there can help with a formula to keep the initial approach with the secret doors.

**Comment by Eligarf** [comment]
The code hack I had to do to make secret doors appear is fundamentally fragile since GM-only functionality is burned into Foundry secret doors at the lowest level. The new approach lets you hide a regular door, making it behave like a secret door from the player's perspective if they don't have the necessary perception to see it.
