### ISSUE TITLE
Hooks or flags to link the rolls to other modules?

### ISSUE THREAD

**Issue by StudioNirin** [Eligarf/stealthy#82]
I am hoping to use Stealthy in conjunction with the Patrol module, so that I can have patrolling guards with automatic 'alerts' when they spot stealthing party members. 
I think this will work using passive perception and passive stealth values, as those are exposed in the actor data, but I was wondering if the 'stealth' and 'spot' rolls from stealthy are also exposed somehow, and what the flag for them might be?

**Comment by Eligarf** [comment]
Currently the values are stored in the effects. I'll look at adding an API hook to get them in a more friendly manner, but for the time being you can look for the 'stealthy' flag on the Spot/Hidden active effects.
```
const hiddenValue = hiddenEffect?.flags.stealthy?.hidden ?? actor.system.skills.ste.passive;
const spotValue = spotEffect?.flags.stealthy?.spot.normal ?? actor.system.skills.prc.passive;
```

**Comment by StudioNirin** [comment]
Ahh thankyou, just so I'm understanding will that set the 'hidden value' to the stealth roll if it exists, and if not it'll set it to the passive stealth? Seems ideal, thankyou

**Comment by Eligarf** [comment]
next release will have an api `const hiddenValue = game.stealthy.getHiddenValue(actor);` which will take care of looking up the effect and dealing with passives. Same for spot. Eventually it will have an option parameter to deal with stuff like lighting or disadvantage or whatever.

**Comment by StudioNirin** [comment]
Awesome. I assume the new api will do the same as the example before? (eg. will show the stealthy value if it exists, but if it doesn't it'll default to the passive?)

**Comment by Eligarf** [comment]
Exactly.
