### ISSUE TITLE
User XXX does not have permission to update token XXXX

### ISSUE THREAD

**Issue by Eligarf** [Eligarf/stealthy#83]
foundry.js:59187 User Player2 lacks permission to update Token [LpWOq7oJP2LwWeD3] in parent Scene [hMxAYM3TXTI0KzrJ]
{modules/ATL/src/activeLighting.js:405 Uncaught (in promise) Error: User Player2 lacks permission to update Token [LpWOq7oJP2LwWeD3] in parent Scene [hMxAYM3TXTI0KzrJ]
[No packages detected]
    at ServerDatabaseBackend._updateEmbeddedDocuments (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4556)
    at async Semaphore._try (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)

Happens on client machine when rolling stealth.

**Comment by Eligarf** [comment]
Modules:
* LightsHUD+ATE
* Stealthy
* Perfectvision
* Warpgate

I also noticed that manual updating of the hidden value stopped working

**Comment by dineshm72** [comment]
My players all also get spammed with these permission errors every time stealth is rolled.  

I also have the above modules installed, except not LightsHUD.

ATE seems to maybe be causing similar errors at other times, so possibly it is the root cause, not sure.

**Comment by dineshm72** [comment]
Yeah, just found this fix to ATE, will test it out and see if it fixes things here: https://github.com/kandashi/Active-Token-Lighting/issues/126

**Comment by dineshm72** [comment]
I've tested the ATE fix.  It fixes a bunch of the permissions errors I was otherwise getting from ATE, but I am still getting the error listed above from Stealthy.  They happen each time Stealth is rolled, and each time you change the hidden stealth value.

Note that unlike what is reported above, I find that I can still manually update the hidden value fine and it works as expected.  (It doesn't work for tokens without Vision set, but that is as expected.)

**Comment by Eligarf** [comment]
I was only able to repro this one time a while back, I'll give it another try.

**Comment by dineshm72** [comment]
I can provide an invite to my game if that would be helpful, you can reach me on discord at dinesh#9364 .

**Comment by Eligarf** [comment]
This bug is inconsistent, but I am confident that LightsHUD+ATE is not a requirement for the issue.

**Comment by dineshm72** [comment]
After some more debugging, one of my other (very old, not recently updated) modules was also giving permission errors for basically the same reason as the ATE errors.

I *think* that ATE was probably causing the errors above.  Now that I've corrected in both ATE and my other module, the permissions errors seem to now be gone.
