### ISSUE TITLE
'Spotted' alert (with pause and symbol)

### ISSUE THREAD

**Issue by StudioNirin** [Eligarf/stealthy#85]
So this currently exists - https://foundryvtt.com/packages/patrol

However Ripper has told me that he doesn't plan to support the spotting/alert aspects of the module anymore, and will just be sticking to the patrolling npcs for it.

However I thought it might be cool to couple it with the stealthy module, to have it so that if an NPC does 'spot' a player, it does the metal-gear-solid style alert and pause. 

Just thought I'd float it as an enhancement idea, as it seems to fit into the theme of this module. 

Edit:
As a secondary thing, if you're not interested in doing this, could I ask what the flags or functions are that you are using, which determine whether a token is visible to another token? 
I know its calculated using spot vs hide but is there an actual flag for ... "is visible" or something, so that I could use it to get all the tokens that are currently visible to a 'spotter' token? 
Thankyou! :)

**Comment by Eligarf** [comment]
So this isn't something I'd see putting in Stealthy itself, but could see it as a very useful module that I'd be happy to help support. I'm not doing any visibility tests/etc in Stealthy; rather, I hooked the existing visibility tests that were already there for the detection modes and added an additional check to reject hidden things from viewers without sufficient perception. I could add a helper function like `Stealthy.DoesViewerSeeTarget(viewer,actor)`

**Comment by Eligarf** [comment]
On second thought, I don't think Stealthy should go beyond supplying the Spot/Hidden values via API. Given the complexities of the differences between how Foundry handles visibility vs how TLC might interpret it for dark/dim status, I don't feel that Stealthy can give a reliable answer beyond doing the comparison of the two skill values, and that isn't adding much value.
