### ISSUE TITLE
(5e) Provide option to use Convenient Effects effect instead of token visibility for non-hidden but not visible tokens

### ISSUE THREAD

**Issue by tnarv** [Eligarf/stealthy#86]
I love the module! It's making running stealth and other darkness related adventures much more immersive and streamlined.

One thing I am running into though is that there are situations where a creature can't be seen but isn't hidden. You can still target the creature with an attack With this module, the token's visibility state changes making it un-targetable.  When using automation workflows like Midi, this can be kind of inconvenient as rolling an attack with being to target skips all that nice automation.

My suggestion is to add a toggle that allows us to set a Convenient Effects effect instead. This would allow the token to be targeted and with an appropriately set up CE allow automation workflows to do their thing.

**Comment by LukasPrism** [comment]
You could still target using the combat tracker (right click)… Mini Tracker makes it even easier (there’s a target button on hostiles in the tracker for players). Also, you can already set up Stealthy to use CE for the conditions … unless I’m misinterpreting?

**Comment by tnarv** [comment]
You can only set it for the hidden condition from what I saw. Which works great!

But if a token can't be perceived visually the module toggles their visibility state. I didn't see an option to change or mess with this. 

I guess I do have a bit of a unique set up since I prefer to hide enemies in the tracker from my players so them not being able to target a token on the canvas directly is an inconvenience. 

Edit: I think this is specifically an issue with Umbral Sight.

**Comment by Eligarf** [comment]
So Umbral sight. yeah. I chose to handle this the same way as invisibility is handled. Makes it simple for me, and if someone has found a good solution for invisibility under normal sight I would think Umbral sight could use the same solution. I'm open to any ideas that unify handling with invisibility. Hiding the token is literally the only "output" that Stealthy uses; my kung-fu is weak still on Foundry. Being able to apply some special effect like Invisibility does one day would super neato, but I have no idea how to do it today.

**Comment by Eligarf** [comment]
There are too many edge conditions at the moment for me to tackle given that there is a targeting solution already present in combat tracker. I'm closing this until some solution becomes clear.
