### ISSUE TITLE
Feature Request  Light Sensitivity automation

### ISSUE THREAD

**Issue by MotoMoto1234** [Eligarf/stealthy#92]
Is it at all possible to automate light sensitivity like the cloakers feature with stealthy sorta like a reverse way you do umbral sight?  

Even if its just a ce/active effect you automate, I can do the rest from there with midi.

**Comment by Eligarf** [comment]
Light level stuff is better handled by a module like [Token Light Condition](https://foundryvtt.com/packages/tokenlightcondition).
