### ISSUE TITLE
Secret Doors

### ISSUE THREAD

**Issue by Vornmegil** [Eligarf/stealthy#93]
Wondering if you're still planning to try to make this work with true secret doors. I like the solution you achieved, however I use foundry for in person gaming around a table mounted screen. If there is no character selected then all hidden doors in vision range show up for everyone. I can stop this from occurring most of the time by ensuring the left click to unselect token option is disabled. however if a character places for example a spell template this automatically deselects the characters therefore displaying all hidden doors.

**Comment by Eligarf** [comment]
No progress is possible on spotting true secret doors until Foundry makes a structural change in the door code. In the meantime, I can at least change the current hidden door code when no tokens are selected to show the hidden doors only if the client is the GM. This should work as you want if you are using something like Monk's Common Display for the player view.

**Comment by Vornmegil** [comment]
Many thanks. You're much appreciated
