### ISSUE TITLE
Issue with Stealthy+MidiQoL+Lib Wrapper+Perfect Vision

### ISSUE THREAD

**Issue by Dyrnwyrm** [Eligarf/stealthy#99]
Issue: When my player tries to select something on the canvas his browser gets stuck until he moves using the arrows.

![image](https://github.com/Eligarf/stealthy/assets/129613553/1c619760-3bea-4580-b398-2af4eb8d3919)

Disabling Stealthy fixes the issue i added the screenshot with the console errors

Foundry Version: 10.291
DnD5e Version: 2.1.5
Stealthy Version: 3.6.0
MidiQoL Version: 10.5.45
Perfect Vision Version: 4.1.20
LibWrapper Version: 1.12.12.1

**Comment by dineshm72** [comment]
I am running the same modules on the same versions, except I am on stealthy 3.5.0, and things seem to work fine, so you can at least downgrade to that version until the issue is fixed.

**Comment by Eligarf** [comment]
I don't understand this one - there was literally no change in any code files between 3.5.0 and 3.6.0, only changes to change log, the phrasing of one friendly stealth option in the language .json files, and an update to what versions of foundry and dnd5e stealthy had been verified with.

Can you perhaps give me more specifics about your player's actor or what exactly they were doing?
